name: build-linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO111MODULE: off

jobs:
  test:
    name: build-linux
    strategy:
      fail-fast: false
      matrix:
        go: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - name: install golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: checkout code
        uses: actions/checkout@v2
      - name: go env
        run: |
          printf "$(go version)\n"
          printf "\n\ngo environment:\n\n"
          go get -u github.com/wubbalubbaaa/easyRpc
          ulimit -n 30000
          go env
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: go test
        run: go test -timeout 60s -coverprofile="./coverage"
      - name: update code coverage report
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./coverage
          flags: unittests
          verbose: true
          name: codecov-easyRpc